---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "nginx-1-config-kjzy"
  namespace: "default"
  labels:
    app: "nginx-1"
data:
  POSTGRES_PASSWORD: "password"
  POSTGRES_USER: "user"
  POSTGRES_DB: "db_name"
  DATABASE_HOST: "database_host"
  DATABASE_PORT: "5432"
  DATABASE_SOCKET: " "
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "nginx-1"
  namespace: "default"
  labels:
    app: "nginx-1"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "nginx-1"
  template:
    metadata:
      labels:
        app: "nginx-1"
    spec:
      containers:
